export const navRoutes = [
  { name: "Home", route: "/" },
  { name: "Page-01", route: "/page1" },
  { name: "Page-02", route: "/page2" },
  { name: "Page-03", route: "/page3" },
  { name: "Page-04", route: "/page4" },
  { name: "Page-05", route: "/page5" },
  { name: "Page-5.2", route: "/page5.2" },
  { name: "Thank You", route: "/thank-you" },
  { name: "Not Found", route: "/not-found" },
  { name: "Contact", route: "/contact" },
  { name: "Page-06", route: "/page6" },
  { name: "Page-07", route: "/page7" },
  { name: "Page-08", route: "/page8" },
  { name: "Page-09", route: "/page9" },
  { name: "Page-10", route: "/page10" },
  { name: "Page-11", route: "/page11" },
];
