import type { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios'

const EUPARTS_END_POINT_URL= process.env.EUPARTS_END_POINT_URL;
const brands = [
  { title: "Abarth", pk: 575 },
  { title: "AC", pk: 576 },
  { title: "Acura", pk: 577 },
  { title: "Aiways", pk: 579 },
  { title: "Aixam", pk: 580 },
  { title: "Alfa Romeo", pk: 583 },
  { title: "Alpina", pk: 584 },
  { title: "Alpine", pk: 585 },
  { title: "ARO", pk: 590 },
  { title: "Artega", pk: 591 },
  { title: "ASKAM", pk: 594 },
  { title: "Aston Martin", pk: 595 },
  { title: "Audi", pk: 598 },
  { title: "Austin", pk: 599 },
  { title: "Autobianchi", pk: 601 },
  { title: "BAIC", pk: 605 },
  { title: "Bentley", pk: 608 },
  { title: "Bertone", pk: 611 },
  { title: "BHARATBENZ", pk: 612 },
  { title: "Bitter", pk: 613 },
  { title: "Bizzarrini", pk: 614 },
  { title: "BMW", pk: 616 },
  { title: "Borgward", pk: 618 },
  { title: "Brilliance", pk: 622 },
  { title: "Bristol", pk: 623 },
  { title: "Bugatti", pk: 624 },
  { title: "Buick", pk: 625 },
  { title: "BUICK", pk: 626 },
  { title: "BYD", pk: 627 },
  { title: "Cadillac", pk: 628 },
  { title: "Caterham", pk: 633 },
  { title: "Chery", pk: 636 },
  { title: "Chevrolet", pk: 637 },
  { title: "Chrysler", pk: 638 },
  { title: "Citroen", pk: 639 },
  { title: "Dacia", pk: 642 },
  { title: "Daewoo", pk: 644 },
  { title: "DAF", pk: 646 },
  { title: "Daihatsu", pk: 647 },
  { title: "Daimler", pk: 648 },
  { title: "DeLorean", pk: 650 },
  { title: "De Tomaso", pk: 653 },
  { title: "Dodge", pk: 655 },
  { title: "DONGFENG", pk: 656 },
  { title: "Donkervoort", pk: 658 },
  { title: "DS", pk: 661 },
  { title: "Eagle", pk: 663 },
  { title: "EICHER", pk: 666 },
  { title: "ERF", pk: 669 },
  { title: "Ferrari", pk: 672 },
  { title: "Fiat", pk: 673 },
  { title: "Fisker", pk: 674 },
  { title: "Ford", pk: 677 },
  { title: "Foton", pk: 679 },
  { title: "FREIGHTLINER", pk: 681 },
  { title: "FSO", pk: 682 },
  { title: "GAZ", pk: 684 },
  { title: "Geely", pk: 685 },
  { title: "Genesis", pk: 686 },
  { title: "GEO", pk: 687 },
  { title: "Ginetta", pk: 689 },
  { title: "GMC", pk: 692 },
  { title: "Great Wall", pk: 695 },
  { title: "HIGER", pk: 700 },
  { title: "Hillman", pk: 701 },
  { title: "Hindustan", pk: 702 },
  { title: "Hino", pk: 703 },
  { title: "Honda", pk: 706 },
  { title: "Hummer", pk: 708 },
  { title: "Hyundai", pk: 709 },
  { title: "Infiniti", pk: 712 },
  { title: "Innocenti", pk: 714 },
  { title: "Irizar", pk: 717 },
  { title: "Isdera", pk: 719 },
  { title: "Iso", pk: 720 },
  { title: "Isuzu", pk: 723 },
  { title: "Iveco", pk: 726 },
  { title: "Jaguar", pk: 728 },
  { title: "Jeep", pk: 729 },
  { title: "Jensen", pk: 730 },
  { title: "KAMAZ", pk: 732 },
  { title: "KENWORTH", pk: 736 },
  { title: "Kia", pk: 737 },
  { title: "King Long", pk: 739 },
  { title: "KOENIGSEGG", pk: 740 },
  { title: "KTM", pk: 741 },
  { title: "Lada", pk: 742 },
  { title: "Lamborghini", pk: 743 },
  { title: "Lancia", pk: 745 },
  { title: "Land Rover", pk: 746 },
  { title: "Lexus", pk: 752 },
  { title: "LEYLAND", pk: 753 },
  { title: "Lifan", pk: 754 },
  { title: "Ligier", pk: 755 },
  { title: "LIGIER", pk: 756 },
  { title: "Lincoln", pk: 757 },
  { title: "Lotus", pk: 758 },
  { title: "MACK", pk: 760 },
  { title: "Mahindra", pk: 762 },
  { title: "MAN", pk: 764 },
  { title: "Marcos", pk: 766 },
  { title: "Maserati", pk: 769 },
  { title: "Maxus", pk: 770 },
  { title: "Maybach", pk: 772 },
  { title: "Maz", pk: 773 },
  { title: "Mazda", pk: 775 },
  { title: "Mclaren", pk: 777 },
  { title: "Mercedes-Benz", pk: 780 },
  { title: "Mercury", pk: 781 },
  { title: "MG", pk: 784 },
  { title: "Microcar", pk: 788 },
  { title: "Mini", pk: 791 },
  { title: "Mitsubishi", pk: 792 },
  { title: "Mitsuoka", pk: 793 },
  { title: "Morgan", pk: 794 },
  { title: "Morris", pk: 795 },
  { title: "NIO", pk: 801 },
  { title: "Nissan", pk: 802 },
  { title: "Oldsmobile", pk: 804 },
  { title: "Oltcit", pk: 805 },
  { title: "Opel", pk: 806 },
  { title: "Osca", pk: 808 },
  { title: "PAGANI", pk: 811 },
  { title: "Panoz", pk: 812 },
  { title: "PEGASO", pk: 814 },
  { title: "Peugeot", pk: 815 },
  { title: "PGO", pk: 816 },
  { title: "Pininfarina", pk: 818 },
  { title: "Plymouth", pk: 820 },
  { title: "Polestar", pk: 821 },
  { title: "Pontiac", pk: 822 },
  { title: "Porsche", pk: 823 },
  { title: "Premier", pk: 824 },
  { title: "Proton", pk: 825 },
  { title: "RAM", pk: 827 },
  { title: "Renault", pk: 831 },
  { title: "Riley", pk: 834 },
  { title: "Rolls-Royce", pk: 835 },
  { title: "Rover", pk: 837 },
  { title: "RUF", pk: 838 },
  { title: "Saab", pk: 839 },
  { title: "Saipa", pk: 840 },
  { title: "Saturn", pk: 843 },
  { title: "Scania", pk: 844 },
  { title: "Seat", pk: 845 },
  { title: "Setra", pk: 846 },
  { title: "SHACMAN", pk: 849 },
  { title: "SISU", pk: 855 },
  { title: "Skoda", pk: 856 },
  { title: "Smart", pk: 857 },
  { title: "Spyker", pk: 862 },
  { title: "Ssangyong", pk: 863 },
  { title: "Subaru", pk: 867 },
  { title: "Suzuki", pk: 869 },
  { title: "Talbot", pk: 870 },
  { title: "TATA", pk: 871 },
  { title: "Tesla", pk: 875 },
  { title: "Toyota", pk: 878 },
  { title: "Triumph", pk: 880 },
  { title: "TVR", pk: 883 },
  { title: "UAZ", pk: 884 },
  { title: "UD TRUCKS", pk: 886 },
  { title: "Vauxhall", pk: 890 },
  { title: "Vector", pk: 892 },
  { title: "Volkswagen", pk: 894 },
  { title: "Volvo", pk: 895 },
  { title: "Wartburg", pk: 897 },
  { title: "WESTERN STAR", pk: 898 },
  { title: "Westfield", pk: 899 },
  { title: "Wiesmann", pk: 900 },
  { title: "Yulon", pk: 907 },
  { title: "Yutong", pk: 908 },
  { title: "Zastava", pk: 909 },
  { title: "ZAZ", pk: 910 },
];

export async function GET(req: NextApiRequest, res: NextApiResponse) {

  return Response.json({brands})

  // try {
  //     axios.get("https://euparts.com.ua/api/carmakes/?format=json").then(res=> {
  //       console.log(res)
  //     return Response.json({});

  //   }).catch(err=>{
  //     throw err;
  //   })

  // } catch (error) {
  //   return Response.json({ error });
  // }


}